### ISSUE TITLE
The plugin caused an error, disabling the plugin fixed it

### ISSUE THREAD

**Issue by loredev10** [tjjfvi/OctoPrint-SlicerSettingsTab#9]
Hello so installing this plugin led to an error.
Looking at the log, it doesn't look to me as related to your module, but disabling the plugin made octoprint run without errors.

```
2023-09-02 10:28:23,021 - octoprint.plugin.core - INFO - Found 33 plugin(s) providing 31 mixin implementations, 60 hook handlers
2023-09-02 10:28:23,160 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2023-09-02 10:28:26,050 - octoprint.cli.server - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/octoprint", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/octoprint/__init__.py", line 1008, in main
    octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/octoprint/cli/server.py", line 317, in serve_command
    run_server(
  File "/usr/lib/python3.10/site-packages/octoprint/cli/server.py", line 163, in run_server
    octoprint_server.run()
  File "/usr/lib/python3.10/site-packages/octoprint/server/__init__.py", line 400, in run
    self._start_intermediary_server()
  File "/usr/lib/python3.10/site-packages/octoprint/server/__init__.py", line 2655, in _start_intermediary_server
    self._intermediary_server.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address in use
2023-09-02 10:40:20,142 - octoprint.startup - INFO - ******************************************************************************
2023-09-02 10:40:20,147 - octoprint.startup - INFO - Starting OctoPrint 1.9.2
2023-09-02 10:40:20,152 - octoprint.startup - INFO - Starting in SAFE MODE. Third party plugins will be disabled!
2023-09-02 10:40:20,152 - octoprint.startup - INFO - Reason for safe mode: problem during last startup
```

**Comment by larsjuhw** [comment]
The log doesn't tell me much unfortunately. Could conflicting with another plugin somehow. Which plugins do you have installed?
